// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FEGLM
Rcpp::List FEGLM(const arma::vec& ky, const arma::mat& kX, const arma::umat& kD, const arma::uvec& klvls_k, const arma::vec& kbeta_start, const arma::vec& kD_alpha_start, const unsigned int kfamily, const Rcpp::List& kctrl);
RcppExport SEXP _alpaca_FEGLM(SEXP kySEXP, SEXP kXSEXP, SEXP kDSEXP, SEXP klvls_kSEXP, SEXP kbeta_startSEXP, SEXP kD_alpha_startSEXP, SEXP kfamilySEXP, SEXP kctrlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type ky(kySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kX(kXSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type kD(kDSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type klvls_k(klvls_kSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type kbeta_start(kbeta_startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type kD_alpha_start(kD_alpha_startSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type kfamily(kfamilySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type kctrl(kctrlSEXP);
    rcpp_result_gen = Rcpp::wrap(FEGLM(ky, kX, kD, klvls_k, kbeta_start, kD_alpha_start, kfamily, kctrl));
    return rcpp_result_gen;
END_RCPP
}
// Kaczmarz
arma::vec Kaczmarz(const arma::vec& kb, const arma::vec& kw_tilde, const arma::umat& kA, const unsigned int kl, const double kc_alpha_tol, const unsigned int kc_trace);
RcppExport SEXP _alpaca_Kaczmarz(SEXP kbSEXP, SEXP kw_tildeSEXP, SEXP kASEXP, SEXP klSEXP, SEXP kc_alpha_tolSEXP, SEXP kc_traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type kb(kbSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type kw_tilde(kw_tildeSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type kA(kASEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type kl(klSEXP);
    Rcpp::traits::input_parameter< const double >::type kc_alpha_tol(kc_alpha_tolSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type kc_trace(kc_traceSEXP);
    rcpp_result_gen = Rcpp::wrap(Kaczmarz(kb, kw_tilde, kA, kl, kc_alpha_tol, kc_trace));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_alpaca_FEGLM", (DL_FUNC) &_alpaca_FEGLM, 8},
    {"_alpaca_Kaczmarz", (DL_FUNC) &_alpaca_Kaczmarz, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_alpaca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
