# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get.alpha <- function(kD_alpha, klvls_k, kA, kB, ktol) {
    .Call(`_alpaca_GetAlpha`, kD_alpha, klvls_k, kA, kB, ktol)
}

pseudo.demeaning <- function(kV, kw, kA, kB, klvls_k, ktol) {
    .Call(`_alpaca_PseudoDemeaning`, kV, kw, kA, kB, klvls_k, ktol)
}

