# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

centerVariables <- function(V, w, klist, tol) {
    .Call(`_alpaca_CenterVariables`, V, w, klist, tol)
}

getAlpha <- function(pi, klist, tol) {
    .Call(`_alpaca_GetAlpha`, pi, klist, tol)
}

groupSums <- function(M, w, jlist) {
    .Call(`_alpaca_GroupSums`, M, w, jlist)
}

groupSumsSpectral <- function(M, v, w, L, jlist) {
    .Call(`_alpaca_GroupSumsSpectral`, M, v, w, L, jlist)
}

groupSumsVar <- function(M, jlist) {
    .Call(`_alpaca_GroupSumsVar`, M, jlist)
}

groupSumsCov <- function(M, N, jlist) {
    .Call(`_alpaca_GroupSumsCov`, M, N, jlist)
}

