# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.feglm <- function(ky, kX, kD, klvls_k, kbeta_start, kD_alpha_start, kfamily, kctrl) {
    .Call(`_alpaca_FEGLM`, ky, kX, kD, klvls_k, kbeta_start, kD_alpha_start, kfamily, kctrl)
}

.kaczmarz <- function(kb, kw_tilde, kA, kl, kc_alpha_tol, kc_trace) {
    .Call(`_alpaca_Kaczmarz`, kb, kw_tilde, kA, kl, kc_alpha_tol, kc_trace)
}

